### ISSUE TITLE
day 9 results wrong

### ISSUE THREAD

**Issue by galgantar** [sguberman/advent2020#1]
Commented results in day 9 are wrong

**Comment by sguberman** [comment]
Hi @galgantar ! Could you be more specific please? The comments match the results I get when I run my code on my puzzle input. And these answers are confirmed correct when I submitted them to the adventofcode website.

Are you talking about something else, or maybe you are getting different answers because your puzzle input is different from mine?

**Comment by galgantar** [comment]
Commented results don't match my confirmed results I get with valid input.

**My results:**

- part 1: 1639024365
- part 2: 219202240

Is it possible that results are not uniformal?

**Comment by sguberman** [comment]
Yes, there are multiple inputs and answers. Closing this issue.
